name = "trader-dashboard"
pages_build_output_dir = "public"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "trader"
database_id = "9047b53e-d8d2-4be6-b46e-c1671c5d2a6e"
