"""Builds a human-readable summary report from the trade/signal/P&L tables.

Printed to stdout at the end of a run (backtest completion, or live/paper
shutdown) so there's a single place to see what the bot actually did
without having to query the SQLite file by hand.
"""
from __future__ import annotations

import os
from datetime import datetime

from storage.db import cursor

# Settings fields relevant to each strategy, dumped into the report header so
# a given run's output can be traced back to the variables that produced it.
_STRATEGY_FIELDS = {
    "orb": (
        "orb_range_minutes", "orb_candle_interval", "orb_volume_multiplier",
        "orb_volume_lookback", "orb_nr7_lookback", "orb_entry_cutoff_time", "orb_target_r",
    ),
    "momentum_halfhour": (
        "momentum_window_minutes", "momentum_volume_multiplier", "momentum_volume_lookback",
    ),
    "pairs": (
        "pairs_config_path", "pairs_spread_lookback", "pairs_entry_z",
        "pairs_exit_z", "pairs_capital_pct",
    ),
}


def build_run_header(settings) -> str:
    """Dumps the run's mode/strategy/capital and whichever strategy-specific
    variables produced it, so a saved report is self-describing and several
    runs' reports can later be compared without cross-referencing .env history."""
    lines = ["=" * 60, "RUN METADATA", "=" * 60]
    lines.append(f"Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"mode: {settings.mode}")
    lines.append(f"strategy: {settings.strategy}")
    lines.append(f"capital: {settings.capital}")
    lines.append(f"risk_pct_per_trade: {settings.risk_pct_per_trade}")
    lines.append(f"daily_loss_cap_pct: {settings.daily_loss_cap_pct}")
    lines.append(f"max_consecutive_errors: {settings.max_consecutive_errors}")
    lines.append(f"slippage_bps: {settings.slippage_bps}")
    for name in _STRATEGY_FIELDS.get(settings.strategy, ()):
        lines.append(f"{name}: {getattr(settings, name)}")
    if settings.strategy == "pairs":
        lines.extend(_build_pairs_config_lines(settings.pairs_config_path))
    lines.append("=" * 60)
    return "\n".join(lines)


def _build_pairs_config_lines(pairs_config_path: str) -> list[str]:
    """Dumps the actual pairs.json contents into the report, since that file
    is gitignored (regenerated by the offline screener) and can silently
    drift between runs -- without this, a saved report can't tell you which
    pairs were actually active when it was produced."""
    lines = [f"active pairs ({pairs_config_path}):"]
    try:
        from strategy.pairs import load_pairs_config
        pairs = load_pairs_config(pairs_config_path)
    except (OSError, ValueError) as exc:
        lines.append(f"  could not read pairs config: {exc}")
        return lines
    for pair in pairs:
        lines.append(f"  {pair.symbol_a}/{pair.symbol_b}: hedge_ratio={pair.hedge_ratio}")
    return lines


def _fetch_all(query: str, params: tuple = ()) -> list[tuple]:
    with cursor() as cur:
        cur.execute(query, params)
        return cur.fetchall()


def build_report(mode: str, open_positions: dict | None = None) -> str:
    lines: list[str] = []
    lines.append("=" * 60)
    lines.append(f"TRADING REPORT (mode={mode})")
    lines.append("=" * 60)

    trades = _fetch_all(
        "SELECT ts, symbol, side, quantity, price, pnl, status, cost, net_pnl FROM trades WHERE mode = ? ORDER BY id",
        (mode,),
    )
    total_cost = sum(t[7] or 0.0 for t in trades)
    closed_trades = [t for t in trades if t[5] is not None]
    total_pnl = sum(t[5] for t in closed_trades)
    total_net_pnl = sum((t[8] if t[8] is not None else t[5]) for t in closed_trades)
    wins = [t for t in closed_trades if (t[8] if t[8] is not None else t[5]) > 0]
    losses = [t for t in closed_trades if (t[8] if t[8] is not None else t[5]) < 0]
    win_rate = (len(wins) / len(closed_trades) * 100) if closed_trades else 0.0

    lines.append(f"Total trade legs (entries + exits): {len(trades)}")
    lines.append(f"Closed round trips: {len(closed_trades)}")
    lines.append(f"Wins: {len(wins)}  Losses: {len(losses)}  Win rate: {win_rate:.1f}% (net basis)")
    lines.append(f"Total transaction costs (brokerage/STT/exchange/GST/stamp duty): {total_cost:.2f}")
    lines.append(f"Gross P&L: {total_pnl:.2f}  |  Net P&L: {total_net_pnl:.2f}")
    if closed_trades:
        avg_win = sum((t[8] if t[8] is not None else t[5]) for t in wins) / len(wins) if wins else 0.0
        avg_loss = sum((t[8] if t[8] is not None else t[5]) for t in losses) / len(losses) if losses else 0.0
        lines.append(f"Avg win (net): {avg_win:.2f}  Avg loss (net): {avg_loss:.2f}")

    by_symbol = _fetch_all(
        """SELECT symbol, COUNT(*), COALESCE(SUM(pnl), 0), COALESCE(SUM(COALESCE(net_pnl, pnl)), 0)
           FROM trades WHERE mode = ? AND pnl IS NOT NULL GROUP BY symbol ORDER BY symbol""",
        (mode,),
    )
    if by_symbol:
        lines.append("")
        lines.append("Per-symbol (closed trades, gross/net P&L):")
        for symbol, count, pnl, net_pnl in by_symbol:
            lines.append(f"  {symbol:<12} trades={count:<4} gross={pnl:.2f}  net={net_pnl:.2f}")

    by_pair = _fetch_all(
        """SELECT pair_id, COUNT(*), COALESCE(SUM(pnl), 0), COALESCE(SUM(COALESCE(net_pnl, pnl)), 0)
           FROM trades WHERE mode = ? AND pair_id IS NOT NULL AND pnl IS NOT NULL GROUP BY pair_id ORDER BY pair_id""",
        (mode,),
    )
    if by_pair:
        lines.append("")
        lines.append("Per-pair (closed legs, both sides combined, gross/net P&L):")
        for pair_id, count, pnl, net_pnl in by_pair:
            lines.append(f"  {pair_id:<24} legs={count:<4} gross={pnl:.2f}  net={net_pnl:.2f}")

    daily = _fetch_all("SELECT trade_date, realized_pnl, trade_count, halted FROM daily_pnl ORDER BY trade_date")
    lines.append("")
    lines.append(f"Trading days recorded: {len(daily)}")
    halted_days = [d for d in daily if d[3]]
    if halted_days:
        lines.append(f"Days halted by loss cap: {len(halted_days)} -> {[d[0] for d in halted_days]}")
    if daily:
        best = max(daily, key=lambda d: d[1])
        worst = min(daily, key=lambda d: d[1])
        lines.append(f"Best day: {best[0]} ({best[1]:.2f})  Worst day: {worst[0]} ({worst[1]:.2f})")

    open_positions = open_positions or {}
    lines.append("")
    if open_positions:
        lines.append(f"WARNING: {len(open_positions)} position(s) still open at report time: {list(open_positions.keys())}")
    else:
        lines.append("All positions closed: yes")

    errors = _fetch_all("SELECT COUNT(*) FROM errors")
    lines.append(f"Errors logged: {errors[0][0]}")
    lines.append("=" * 60)

    if trades:
        lines.append("")
        lines.append("All trades:")
        lines.append(
            f"  {'ts':<28}{'symbol':<12}{'side':<6}{'qty':>6}  {'price':>10}  {'cost':>8}  {'gross':>10}  {'net':>10}  status"
        )
        for ts, symbol, side, quantity, price, pnl, status, cost, net_pnl in trades:
            pnl_str = f"{pnl:.2f}" if pnl is not None else "-"
            net_str = f"{net_pnl:.2f}" if net_pnl is not None else "-"
            lines.append(
                f"  {ts:<28}{symbol:<12}{side:<6}{quantity:>6}  {price:>10.2f}  {cost:>8.2f}  {pnl_str:>10}  {net_str:>10}  {status}"
            )
        lines.append("=" * 60)

    return "\n".join(lines)


def print_report(mode: str, open_positions: dict | None = None) -> None:
    print(build_report(mode, open_positions))


def write_report(
    mode: str,
    settings,
    open_positions: dict | None = None,
    extra: str = "",
    base_dir: str = "reports",
) -> str:
    """Writes the report to a timestamped subfolder (for later reference/diffing
    across runs) and also prints it to stdout, so the run's outcome is visible
    immediately without opening the file. Each run gets its own folder (named
    by timestamp, mode, and strategy) so multiple runs' reports can be kept
    side by side and later collated. Returns the path written."""
    run_dir = os.path.join(
        base_dir, f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{mode}_{settings.strategy}"
    )
    os.makedirs(run_dir, exist_ok=True)
    path = os.path.join(run_dir, "report.txt")

    report = build_run_header(settings) + "\n" + build_report(mode, open_positions)
    if extra:
        report = extra + "\n" + report
    with open(path, "w") as f:
        f.write(report)
    print(report)
    print(f"Report written to {path}")
    return path
